# 工作流名称
name: Check Notion Links

# 触发器
on:
  schedule:
    # 每天 UTC 时间 1:00 AM 运行 (对应北京时间早上 9:00 AM)
    - cron: '0 1 * * *'
  workflow_dispatch:

# 任务
jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- [OPTIMIZATION] ---
      # 缓存 Playwright 的浏览器二进制文件
      - name: Cache Playwright browsers
        id: playwright-cache # 给这个步骤一个 ID，方便后续引用
        uses: actions/cache@v4
        with:
          # Playwright 在 Linux 系统下的默认缓存路径
          path: ~/.cache/ms-playwright
          # 缓存的 key。当 package-lock.json 变化时（意味着 Playwright 版本可能更新），key 会变化，缓存会失效
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          # 如果 key 完全匹配不上，会尝试使用这个模糊匹配来恢复一个旧缓存
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: npm ci

      # --- [OPTIMIZATION] ---
      # 只有在没有命中缓存的情况下，才执行安装步骤
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium # 只安装我们需要的 chromium 内核

      # 运行脚本
      - name: Run link checker script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: npm start
