# 工作流名称
name: Check Notion Links

# 触发器
on:
  schedule:
    # 每天 UTC 时间 1:00 AM 运行 (对应北京时间早上 9:00 AM)
    - cron: '0 1 * * *'
  workflow_dispatch:

# 任务
jobs:
  check-links:
    runs-on: ubuntu-latest
    # 增加超时设置，因为安装和运行 Playwright 可能耗时较长
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 新增：缓存依赖，加快后续运行速度
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 修改：使用 npm ci 更快更可靠地安装依赖
      - name: Install dependencies
        run: npm ci

      # 新增：安装 Playwright 所需的浏览器二进制文件
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 运行脚本
      - name: Run link checker script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: npm start
